name: Deploy

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      url:
        required: true
        type: string
      type:
        required: false
        type: string
        default: 'testing'
    secrets:
      HEROKU_API_KEY:
        required: true
      JIRA_URL:
        required: true
      JIRA_CLIENT_ID:
        required: true
      JIRA_CLIENT_SECRET:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: Load Cache
        uses: frango9000/cache@main
        env:
          cache-key: ${{ runner.os }}-v4
        with:
          path: |
            ~/.m2
            ~/.npm
            ./node_modules
            ./node
          key: ${{ env.cache-key }}-${{ steps.branch-name.outputs.current_branch }}-${{ github.run_id }}
          restore-keys: |
            ${{ env.cache-key }}-${{ steps.branch-name.outputs.current_branch }}
            ${{ env.cache-key }}-development
            ${{ env.cache-key }}
          save-on-hit: true

      - name: Java Dependencies
        run: mvn -f apps/api/pom.xml dependency:resolve dependency:resolve-plugins

      - name: Node Dependencies
        run: yarn install

      - name: Set Deployment Status In Progress
        uses: bobheadxi/deployments@v1.3.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ inputs.env }}

      - name: Deploy to Heroku
        uses: MansaGroup/nrwl-nx-action@v2
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          targets: deploy
          all: 'true'
          parallel: 'false'
          affected: 'false'
          args: '--configuration=${{ inputs.env }}'

      - name: Upload Deployed Artifact
        uses: actions/upload-artifact@v3
        with:
          name: production-package
          path: apps/api/target/*.jar

      - name: Update Deployment Status
        uses: bobheadxi/deployments@v1.3.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ inputs.url }}

      - name: Failed Deployment
        if: failure()
        run: echo "DEPLOY_STATE=failed" >> $GITHUB_ENV

      - name: Successful Deployment
        if: success()
        run: echo "DEPLOY_STATE=successful" >> $GITHUB_ENV
